name: Build Padavan for Xiaomi Router 3G

on:
  
  release:
    types: published
  schedule:
    - cron: 0 16 * * *
  watch:
    types: started

env:
  TNAME: MI-R3G
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: false

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/hanwckf/rt-n56u /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        mkdir -p toolchain-3.4.x
        wget https://github.com/hanwckf/padavan-toolchain/releases/download/v1.1/mipsel-linux-uclibc.tar.xz
        tar -xvf mipsel-linux-uclibc.tar.xz -C toolchain-3.4.x
        mkdir -p /opt/images/
        sed -i '/cp -f configs\/templates\/\$1.config .config/d' /opt/rt-n56u/trunk/build_firmware_modify

    - name: Edit .config
      run: |
        cp -f diy.sh /opt/rt-n56u/trunk/
        cd /opt/rt-n56u/trunk/
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "$TNAME.config not found "
        exit 1
        fi
        cp -f configs/templates/$TNAME.config .config
        chmod +x diy.sh
        sh diy.sh

    - name: Build Firmware
      run: |
        cd /opt/rt-n56u/trunk
        sudo ./clear_tree
        sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /opt/images/

    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images